.TH LILO 7 2009-07-12 "Linux" "Linux Users's Manual"
.SH 名前
LILO \- Linux Install Learning Osaka ; 読みは「りろ」。
.SH 書式
主な使い方:
.LP
.B " LMS"
\- LILO Monthly Seminar
.LP
他の使い方:
.LP
.B " LILO ML "
\- LILO メーリングリスト
.br
.B " イベント"
\- セミナー/オフラインミーティング
.br
.B " サブプロジェクト"
.br
.B " 宴会の開催(実はこれがメインだったり...)"
.br
.SH 説明
.LP
.B LILO
(りろ : Linux Install Learning Osaka) は関西の Linux ユーザ会です。
主に関西の Linux ユーザの交流、情報交換の場を提供するために活動しています。
.br
関西の地域
.BI "LUG (Linux User Group) " "(http://www.linux.or.jp/community/group/index.html)"
になります。 
.LP
.SS メーリングリスト(LILO ML)による情報交換
.PP
LILO メーリングリスト (
.I LILO ML
) は、(関西地区の) Linux ユーザのメーリングリストです。
.I LILO ML
に入るには、
.B 関西大好きな人
から、関西とはなんの関係もない人けどとにかく入りたい人まで、入りたい気持ちがあれば、どなたでも参加 OK です。
.br
このメーリングリストでは、 :
.TP
.B Linux に関するよもやま話
.TP
.B LILO インストールセミナー/オフラインミーティングの準備/連絡
.TP
.B Linux での自作ソフト、ハードの自慢話
.TP
.B Linux に関するソフト、ハードの実績報告
.TP
.B 既存のコンピュータ ML に収まらない話題
.br
以上のようなことを主な話題にしています。
.SS セミナー/オフラインミーティング
.PP
LILO では、不定期にセミナーやミーティングを開いています(もちろん宴会も！)。明確には分類できないのですが、一応 以下のような種類があります。
.TP
.B インストールセミナー
Linux のインストールや、使い方などの講義があります。比較的、フォーマルな形で行われることが多いです。
.TP
.BI "LILO Monthly Seminar" (LMS)
「Linux に興味はあるけど、どう使えばエエのかよう分かりまへんねん」という方のために、テーマを少しずつ変えながら毎月1回開催する(予定の(^^;;) 「Linux 使いこなし講座」です。
.TP
.B LILO オフラインミーティング
.I LILO ML
のメンバー中心に、朝から晩まで、Linux ネタで盛り上ったり、マシン持ち込んで自慢したり、うだうだします。猫の集会とも言われています(笑)。もちろん、
.I LILO ML
メンバーでない方も参加大歓迎です。LILO の原点ですね。
.TP
.B 他団体との合同セミナー
LILO は、他の団体と合同でイベントを行うこともあります。 Linux に関係する団体はもちろん、Linux に関係しない団体でも、 LILO に関係する内容ならば、一緒にイベントをやりましょう。
.TP
.B 宴会
LILO のメンバーが一番楽しみにしていることです(爆笑)。
.br
注意) ラテン系のダンスチームが出没することがあります。
.PP
LILO は Linux 好きが集まったボランティアベースのユーザ団体です。 LILO として、インストールセミナー等の集会を企画することがありますが、インストールに失敗することもありますし、ご希望にそえない場合も多くあります。あくまで、LILO はイントール等のお手伝いをするだけです。その点は、あらかじめ御了承ください。 
.SS LILO Sub-Project
.PP
LILO には、
.I Sub-Project(サブプロジェクト)
というものがあります。特定の目的や専門性をもったプロジェクトを動かしたかったり、
同じ趣味を持つ人達でワイワイと騒ぎたかったりするため :-)、 
.I LILO ML
で話すより、別 ML を立てた方が良いと判断される場合に
.I Sub-Project
が発足します。基本的には、
.I LILO ML
内でメンバーを募ります。活動は、その Sub-Project の ML でしてもらいますが、活動報告等を 
.I LILO ML
に流すこともあります。 
.br
.I Sub-Project
のためのきまりやルールといったものは明確には決っていませんが、
.TP 3
1.
.I LILO ML
のメンバーは誰でも、
.I Sub-Project
発足の提案ができる。
.TP 3
2.
.I Sub-Project
には、中心的人物(代表)がいる。(主に言い出しっぺ ^^)
.TP 3
3.
中心的人物には、
.I LILO ML
に入っているメンバーがなる。
.TP 3
4.
.I サブプロジェクト
は、LILO の資源を使える。
.TP 3
5.
.I サブプロジェクト
での成果は、LILO にフィードバックしてもらう。
.PP
などです。あくまで、ゆるやかな取り決めですので絶対に守るべきルールではありません。メンバーになるのは、
.I LILO ML
に入っていることが必須条件では ありませんが、
.I LILO ML
に入っている方が望ましいと思います。 
.SS その他 LILO の活動
.TP
.B IRC チャット
IRC による日常会話「#lilo:*.jp」で待ってまっせ〜 
.SS 発表資料等
LILO の活動の中で、使われた資料などを置いています。
.TP
28th Linux Seminar 資料
.B "「バージョン管理ツール CVS を使おう」"
.I http://lilo.linux.or.jp/lilo-doc/docs2/use_cvs/index.html
.TP
RealTeam JUS 勉強会資料
.BI "「Linux のみを使った RealSystem 構築について」 " http://lilo.linux.or.jp/JUS20000209/
.TP
.B "「Linux で RealVideo Live! -Linux を使った RealSystem構築入門-」"
.I http://www.netfort.gr.jp/%7Etosihisa/RealSystem/LinuxReal.html
.PP
.I LILO Monthly Seminar
などに関する資料は
.BI Wiki (http://lilo.linux.or.jp/wiki/)
にまとめていますのでご覧ください。
各
.BI サブプロジェクト (http://lilo.linux.or.jp/sub_project/)
のページもご覧ください。 
.SH 歴史 
.TP
.B 1997-06-19
linux-users ML で関西の Linux ユーザの集まりが提案される。
.br
.B "[linux-users:06937] Re: [ANNOUNCE] Linux users kyusyu area meeting"
.I http://search.luky.org/linux-users.0/msg06694.html
.TP
.B 1997-06-22
正式名称決定。ML 開設。 
.br
.B "[linux-users:07068] Osaka Meeting"
.I http://search.luky.org/linux-users.0/msg06819.html
.TP
.B 1997-07-21
第1回オフラインミーティング開催。
.br
.B "ミニミーティング in(株)リステム"
.I http://lilo.linux.or.jp/event/lilo_1st/
.TP
.B 2007-07-21
.B "LMS番外編 爆笑LILO10年史 (オープンソースカンファレンス2007 kansai)"
.I http://lilo.linux.or.jp/wiki/lms/20070721
.SH バグ
.TP
.B LILO
ブートローダの　
.BI "LILO" (8)
をもじって命名されているため
.I ブートローダ
のコミュニティと勘違いされます。
.br
.TP
.BI "LILO Monthly Seminar" (LMS)
.I LMS
は、毎月1回開催する予定となっていますが、開けていないことから開催のアナウンスが必ず流れる
.I LILO ML
に入っておくと安心です。
.SH 関連項目
luky(7), luck(7), lilo(8).
.SH 著者
LILO Webmasters <webmasters@lilo.linux.or.jp> (元になったホームページの管理者)
.br
Nobuyuki Maruichi <HFD03621@nifty.ne.jp> (加筆修正、フォーマット調整)
